FROM redhat/ubi8

COPY checkmon.c /
COPY server.c   /
COPY serverd    /

WORKDIR /

RUN dnf install -y gcc make vim iputils wget hostname procps-ng

RUN gcc /checkmon.c -o /checkmon
RUN gcc /server.c -o /server
RUN chmod a+x /serverd
CMD bash /serverd
